# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release upload deploy

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: latest_prod

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Restore Go Module Cache
      id: restore-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build for multiple platforms
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bangumi_main
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bangumi_main.exe

    - name: upload artifact
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          bangumi_main
          bangumi_main.exe
