# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release upload deploy

on:
  push:
    branches: [ "prod" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build for multiple platforms
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bangumi_main
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bangumi_main.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bangumi_main
          bangumi_main.exe
